apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort  # Changed from LoadBalancer to NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32499
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-activity-alohachloe
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-html
        image: curlimages/curl
        command: ["sh", "-c", "curl -o /usr/share/nginx/html/index.html https://raw.githubusercontent.com/alohachloe/Kubernetes/main/index.html"]
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        command: [ "nginx", "-g", "daemon off;" ]
      volumes:
      - name: html-volume
        emptyDir: {}
